### ISSUE TITLE
Mirroring Effect in Result

### ISSUE THREAD

**Issue by Mayur28** [hhj1897/face_pose_augmentation#14]
Hi,

I've been experimenting with the solution which seems to work fantastically most of the time, but I noticed that in some cases, the result exhibits a mirroring effect which I wanted to find out if you have any ideas on how to eliminate it. Please refer to the image attached below to see what I am referring to. Note that the blinking and mouth movements are a "perfect reflection" of the proper face.

![image](https://user-images.githubusercontent.com/26574827/204139026-f8779be1-c17f-4d4c-b117-458277321ee6.png)
![image](https://user-images.githubusercontent.com/26574827/204139107-717f271b-ac9b-468c-962e-4441089f41b5.png)

**Comment by hhj1897** [comment]
This is likely because you tried to turn face toward the opposite direction. Please note the tool is only designed to make the face turn more toward the side, not less, nor to make it turn toward the opposite direction. Namely, if the detected yaw > 0, delta yaw should also > 0, and vice versa. In case if want to balance the distribution of yaw, you can add a random horizontal flip after using this tool.

**Comment by Mayur28** [comment]
Understood, thank you for the clarification.
