### ISSUE TITLE
What is the purpose of function `model_completion_bfm`? 

### ISSUE THREAD

**Issue by jimmysue** [hhj1897/face_pose_augmentation#8]

**Comment by jacksoncsy** [comment]
Hey @jimmysue, this function tries to complete a full head using the some parts from FaceWarehouse model. Since 3DDFA fitting result cover only the main face region (no back head, no ears, no neck), augmenting using this mesh is difficult and error prone. Thus, we need to complete the face mesh before using it for augmentation. I hope this answers your question well?

**Comment by AaboutL** [comment]
> Hey @jimmysue, this function tries to complete a full head using the some parts from FaceWarehouse model. Since 3DDFA fitting result cover only the main face region (no back head, no ears, no neck), augmenting using this mesh is difficult and error prone. Thus, we need to complete the face mesh before using it for augmentation. I hope this answers your question well?

@jacksoncsy But in 3DDFA_V1's training code, the shape of w_exp_sim.npy in train.configs folder is (159645, 10). 159645 is corresponding to  53215 points which contains ears and neck. Why did you say "3DDFA fitting result cover only the main face region (no back head, no ears, no neck)" ? I am really confused about this.
